import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from 'react';
import io from 'socket.io-client';
import ChatComponent from "./components/Chat";

const socket = io();

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  // const [messages, setMessages] = useState([]);
  // const [input, setInput] = useState('');

  // useEffect(() => {
  //   // Listen for incoming messages
  //   socket.on('message', (message) => {
  //     setMessages((prevMessages) => [...prevMessages, message]);
  //   });

  //   // Clean up the socket connection when the component unmounts
  //   return () => {
  //     socket.disconnect();
  //   };
  // }, []);

  // const sendMessage = () => {
  //   if (input.trim() !== '') {
  //     // Send the message to the server
  //     socket.emit('message', { text: input, timestamp: new Date().toISOString() });
  //     setInput('');
  //   }
  // };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <ChatComponent />
        </div>

        {/* <h1>Chat App</h1>
        <div>
          {messages.map((message, index) => (
            <div key={index}>{`${message.text} - ${message.timestamp}`}</div>
          ))}
        </div>
        <div>
          <input type="text" value={input} onChange={(e) => setInput(e.target.value)} />
          <button onClick={sendMessage}>Send</button>
        </div> */}
      </main>
    </>
  );
}
